{{- if .Values.server.secretEnv -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "<CHARTNAME>.name" . }}
    chart: {{ include "<CHARTNAME>.chart" . }}
    release: {{ .Release.Name }}
    helm.sh/chart: {{ include "<CHARTNAME>.chart" . }}
    app.kubernetes.io/name: {{ include "<CHARTNAME>.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.server.secretEnv }}
{{ $key | indent 2 }} : {{ tpl $value $ | b64enc | quote}}
{{- end }}
{{- end }}
